"""
Mesh I/O utilities for HydroSIS-2D

Handles mesh import/export in various formats.
"""

import numpy as np
from typing import Optional, Dict, Any
import logging
import json

from .mesh_generator import StructuredMesh, DomainParams, MeshParams

logger = logging.getLogger(__name__)


class MeshIO:
    """
    Mesh input/output handler

    Supports multiple formats:
        - HydroSIS-2D INI format
        - VTK format (for visualization)
        - JSON format (for metadata)
        - NumPy binary format (for data arrays)
    """

    @staticmethod
    def export_to_ini(mesh: StructuredMesh, filepath: str,
                     include_physics: bool = True) -> None:
        """
        Export mesh to HydroSIS-2D INI configuration file

        Args:
            mesh: StructuredMesh to export
            filepath: Output file path
            include_physics: Include default physics parameters
        """
        with open(filepath, 'w') as f:
            f.write("# HydroSIS-2D Configuration File\n")
            f.write("# Generated by prepost mesh generator\n\n")

            # Grid section
            f.write("[Grid]\n")
            f.write(f"nx = {mesh.nx}\n")
            f.write(f"ny = {mesh.ny}\n")
            f.write(f"dx = {mesh.dx:.6f}\n")
            f.write(f"dy = {mesh.dy:.6f}\n")
            f.write(f"xmin = {mesh.domain.xmin:.6f}\n")
            f.write(f"ymin = {mesh.domain.ymin:.6f}\n")
            f.write(f"xmax = {mesh.domain.xmax:.6f}\n")
            f.write(f"ymax = {mesh.domain.ymax:.6f}\n\n")

            if include_physics:
                f.write("[Physics]\n")
                f.write("gravity = 9.81\n")
                f.write("cfl = 0.5\n")
                f.write("h_dry = 1e-4\n")
                f.write("friction_type = 0  # 0: Manning, 1: Chezy\n\n")

                f.write("[Time]\n")
                f.write("t_start = 0.0\n")
                f.write("t_end = 100.0\n")
                f.write("dt_max = 1.0\n")
                f.write("output_interval = 5.0\n\n")

                f.write("[Boundary]\n")
                f.write("bc_left = 0    # 0: wall, 1: open, 2: inflow, 3: outflow\n")
                f.write("bc_right = 0\n")
                f.write("bc_bottom = 0\n")
                f.write("bc_top = 0\n\n")

                f.write("[Solver]\n")
                f.write("use_lts = false\n")
                f.write("riemann_solver = 1  # 1: HLLC\n")
                f.write("slope_limiter = 0   # 0: minmod\n")
                f.write("order = 2           # 2: second-order MUSCL\n")

        logger.info(f"Exported mesh to INI format: {filepath}")

    @staticmethod
    def export_to_vtk(mesh: StructuredMesh, filepath: str,
                     data_arrays: Optional[Dict[str, np.ndarray]] = None) -> None:
        """
        Export mesh to VTK structured grid format

        Args:
            mesh: StructuredMesh to export
            filepath: Output file path (.vtk)
            data_arrays: Optional dictionary of data arrays to include
                        Keys are field names, values are 2D numpy arrays
        """
        with open(filepath, 'w') as f:
            # VTK header
            f.write("# vtk DataFile Version 3.0\n")
            f.write("HydroSIS-2D Mesh\n")
            f.write("ASCII\n")
            f.write("DATASET STRUCTURED_GRID\n")

            # Grid dimensions (points, not cells)
            f.write(f"DIMENSIONS {mesh.nx+1} {mesh.ny+1} 1\n")
            f.write(f"POINTS {(mesh.nx+1)*(mesh.ny+1)} float\n")

            # Write point coordinates
            for j in range(mesh.ny + 1):
                y = mesh.domain.ymin + j * mesh.dy
                for i in range(mesh.nx + 1):
                    x = mesh.domain.xmin + i * mesh.dx
                    f.write(f"{x:.6f} {y:.6f} 0.0\n")

            # Write cell data if provided
            if data_arrays:
                f.write(f"\nCELL_DATA {mesh.ncells}\n")

                for name, data in data_arrays.items():
                    if data.shape != (mesh.nx, mesh.ny):
                        logger.warning(f"Data array '{name}' has wrong shape, skipping")
                        continue

                    f.write(f"\nSCALARS {name} float 1\n")
                    f.write("LOOKUP_TABLE default\n")

                    # Write data in row-major order
                    for j in range(mesh.ny):
                        for i in range(mesh.nx):
                            f.write(f"{data[i, j]:.6e}\n")

        logger.info(f"Exported mesh to VTK format: {filepath}")

    @staticmethod
    def export_to_json(mesh: StructuredMesh, filepath: str) -> None:
        """
        Export mesh metadata to JSON format

        Args:
            mesh: StructuredMesh to export
            filepath: Output file path (.json)
        """
        metadata = {
            'type': 'StructuredMesh',
            'nx': mesh.nx,
            'ny': mesh.ny,
            'ncells': mesh.ncells,
            'dx': mesh.dx,
            'dy': mesh.dy,
            'domain': {
                'xmin': mesh.domain.xmin,
                'xmax': mesh.domain.xmax,
                'ymin': mesh.domain.ymin,
                'ymax': mesh.domain.ymax,
                'length_x': mesh.domain.length_x,
                'length_y': mesh.domain.length_y,
                'area': mesh.domain.area
            },
            'properties': {
                'cell_area': mesh.get_cell_area(),
                'aspect_ratio': mesh.aspect_ratio
            }
        }

        with open(filepath, 'w') as f:
            json.dump(metadata, f, indent=2)

        logger.info(f"Exported mesh metadata to JSON: {filepath}")

    @staticmethod
    def export_coordinates(mesh: StructuredMesh, filepath: str) -> None:
        """
        Export mesh coordinates to NumPy binary format

        Args:
            mesh: StructuredMesh to export
            filepath: Output file path (.npz)
        """
        np.savez(filepath,
                x=mesh.x,
                y=mesh.y,
                nx=mesh.nx,
                ny=mesh.ny,
                dx=mesh.dx,
                dy=mesh.dy)

        logger.info(f"Exported mesh coordinates to NPZ: {filepath}")

    @staticmethod
    def import_from_json(filepath: str) -> StructuredMesh:
        """
        Import mesh from JSON metadata file

        Args:
            filepath: Input JSON file path

        Returns:
            Reconstructed StructuredMesh
        """
        with open(filepath, 'r') as f:
            metadata = json.load(f)

        domain = DomainParams(
            xmin=metadata['domain']['xmin'],
            xmax=metadata['domain']['xmax'],
            ymin=metadata['domain']['ymin'],
            ymax=metadata['domain']['ymax']
        )

        mesh_params = MeshParams(
            nx=metadata['nx'],
            ny=metadata['ny'],
            dx=metadata['dx'],
            dy=metadata['dy']
        )

        mesh = StructuredMesh(domain, mesh_params)
        logger.info(f"Imported mesh from JSON: {filepath}")

        return mesh

    @staticmethod
    def export_batch(mesh: StructuredMesh, output_dir: str,
                    base_name: str = "mesh") -> Dict[str, str]:
        """
        Export mesh to multiple formats at once

        Args:
            mesh: StructuredMesh to export
            output_dir: Output directory
            base_name: Base filename (without extension)

        Returns:
            Dictionary mapping format to filepath
        """
        import os
        os.makedirs(output_dir, exist_ok=True)

        outputs = {}

        # INI format
        ini_path = os.path.join(output_dir, f"{base_name}.ini")
        MeshIO.export_to_ini(mesh, ini_path)
        outputs['ini'] = ini_path

        # VTK format
        vtk_path = os.path.join(output_dir, f"{base_name}.vtk")
        MeshIO.export_to_vtk(mesh, vtk_path)
        outputs['vtk'] = vtk_path

        # JSON format
        json_path = os.path.join(output_dir, f"{base_name}.json")
        MeshIO.export_to_json(mesh, json_path)
        outputs['json'] = json_path

        # NumPy format
        npz_path = os.path.join(output_dir, f"{base_name}.npz")
        MeshIO.export_coordinates(mesh, npz_path)
        outputs['npz'] = npz_path

        logger.info(f"Exported mesh to {len(outputs)} formats in {output_dir}")

        return outputs
